# Vertical Candidate List
Vertical Candidate List=False
# Per Screen DPI
PerScreenDPI=True
# Use mouse wheel to switch page when mouse is over candidate window
WheelForPaging=True
# Font
Font="Sans 16"
# Theme
Theme=default
